# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.TextField()),
                ('emp_id', models.IntegerField()),
                ('emp_phone', models.IntegerField()),
                ('emp_address', models.CharField(max_length=150)),
            ],
        ),
    ]
